apiVersion: apps/v1
kind: Deployment
metadata: 
    name: my-app-deployment1
spec: 
  selector: 
    matchLabels: 
            name: my-app1
  template:
    metadata:
          labels: 
              name: my-app1
    spec: 
        containers: 
            - name: gcp-test
              image: sholehbaktiabadi/gcp-test:0.0.2
              env: 
                - name: APP_PORT
                  value: "5522"
                - name: NODE_ENV
                  value: "DEV"

                - name: DB_HOST
                  value: "some-mysql"
                - name: DB_PORT
                  value: "3306"
                - name: DB_NAME
                  value: "local"
                - name: DB_USER
                  value: "root"
                - name: DB_PASSWORD
                  value: "my-secret-pw"
                          
                          