apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment1
spec: 
  selector: 
    matchLabels:
      name: my-app2
  template: 
    metadata:
      labels:
        name: my-app2
    spec: 
      containers:
        - name: container-mysql
          image: mysql:latest
          args: 
            - --init-file
            - /shared-files/4-schema.sql
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: mysql-credential
                  key: mysql-root-password
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts: 
            - name: db-data
              mountPath: /var/lib/mysql
            - name: root
              mountPath: /shared-files
      volumes: 
        - name: db-data
          hostPath: 
            path: /data/volume-example
        - name: root
          hostPath: 
            path: /

---
apiVersion: v1
kind: Service
metadata: 
  name: my-service2
spec: 
  type: ClusterIP
  selector: 
    name: my-app2
  ports: 
    - port: 3306
      targetPort: 3306
--- 
apiVersion: v1
kind: Secret
metadata: 
  name: mysql-credential
type: Opaque
data: 
  mysql-root-password: UGFzc3dvcmQxIQ==
---